# https://docs.getdbt.com/reference/dbt_project.yml
name: 'project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

packages-install-path: dbt_packages

vars:
  surrogate_key_treat_nulls_as_empty_strings: true

# Configuring models:
# https://docs.getdbt.com/reference/configs-and-properties
# https://docs.getdbt.com/reference/model-properties
# https://docs.getdbt.com/reference/model-configs
# https://docs.getdbt.com/docs/build/materializations
# https://docs.getdbt.com/reference/resource-configs/plus-prefix
models:
  +persist_docs:
    relation: true
    columns: true
  project:
    marts:
      +materialized: table
      attendance:
        +schema: attendance
        +tags: edfi
        +group: edfi_amt
      core:
        +schema: core
        +tags: edfi
        +group: edfi_amt
      row_level_security:
        +schema: row_level_security
        +tags: edfi
        +group: edfi_amt
    staging:
      +materialized: table
      +schema: staging
      edfi:
        +tags: edfi
        +group: edfi_staging
        +labels:
            edfi_version: "5_3"

